<?php

$category_list = array(
1	=> 'Arts & Entertainment',
2	=> 'Betting',
272	=> 'Betting Systems',
3	=> 'Business / Investing',
4	=> 'Computers / Internet',
5	=> 'Cooking, Food & Wine',
6	=> 'E-business & E-marketing',
7	=> 'Education',
8	=> 'Employment & Jobs',
9	=> 'Fiction',
10	=> 'Games',
11	=> 'Green Products',
12	=> 'Health & Fitness',
13	=> 'Home & Garden',
14	=> 'Languages',
15	=> 'Mobile',
16	=> 'Parenting & Families',
17	=> 'Politics / Current Events',
18	=> 'Reference',
19	=> 'Self-Help',
20	=> 'Software & Services',
21	=> 'Spirituality, New Age & Alternative Beliefs',
22	=> 'Sports',
23	=> 'Travel',
);